# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ecugol/pre-commit-hooks-django
    rev: v0.3.0
    hooks:
      - id: check-untracked-migrations
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        types:
          - python
      - id: end-of-file-fixer
        types:
          - python
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: 'migrations|local_settings.py'
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys, --expand-star-imports]
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        exclude: 'migrations'
        args:
          - --profile=black
          - --line-length=120
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: 'migrations'
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - "flake8-simplify==0.14.1"
        args:
          - --max-line-length=120
          - --extend-ignore=E203, W503, F405, SIM105, SIM106, SIM119
  - repo: https://github.com/rtts/djhtml
    rev: 'v1.4.9'
    hooks:
      - id: djhtml
        args:
        - --tabwidth=2
        files: 'templates/'
