# Generated by Django 3.0.8 on 2020-10-31 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amortizatia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_amortizatia', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 15, 741994), verbose_name='Дата')),
                ('ostatoc_amortizatia', models.CharField(max_length=255)),
                ('sum_amortizatia', models.CharField(max_length=255)),
                ('describe_amortizatia', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Амортизация',
                'verbose_name_plural': 'Амортизация',
                'ordering': ['-date_amortizatia', '-id'],
            },
        ),
        migrations.CreateModel(
            name='eda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_eda', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 15, 741994), verbose_name='Дата')),
                ('ostatoc_eda', models.CharField(max_length=255)),
                ('sum_eda', models.CharField(max_length=255)),
                ('describe_eda', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еда',
                'ordering': ['-date_eda', '-id'],
            },
        ),
        migrations.CreateModel(
            name='minfin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_minfin', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 15, 741994), verbose_name='Дата')),
                ('ostatoc_minfin', models.CharField(max_length=255)),
                ('sum_minfin', models.CharField(max_length=255)),
                ('describe_minfin', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Минфин',
                'verbose_name_plural': 'Минфин',
                'ordering': ['-date_minfin', '-id'],
            },
        ),
        migrations.CreateModel(
            name='nds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_nds', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 15, 741994), verbose_name='Дата')),
                ('ostatoc_nds', models.CharField(max_length=255)),
                ('sum_nds', models.CharField(max_length=255)),
                ('describe_nds', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ндс',
                'verbose_name_plural': 'Ндс',
                'ordering': ['date_nds', '-id'],
            },
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_nlg', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 15, 741994), verbose_name='Дата')),
                ('text_nlg', models.TextField(verbose_name='Текст')),
                ('image_nlg', models.ImageField(blank=True, upload_to='foto\\%Y\\%m\\%d', verbose_name='Фотоверсия')),
            ],
            options={
                'verbose_name': 'Нлж',
                'verbose_name_plural': 'Нлж',
                'ordering': ['-date_nlg', '-id'],
            },
        ),
        migrations.CreateModel(
            name='prochee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prochee', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 15, 741994), verbose_name='Дата')),
                ('ostatoc_prochee', models.CharField(max_length=255)),
                ('sum_prochee', models.CharField(max_length=255)),
                ('describe_prochee', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Прочее',
                'verbose_name_plural': 'Прочее',
                'ordering': ['-date_prochee', '-id'],
            },
        ),
        migrations.CreateModel(
            name='razvlechenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_razvlechenia', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 15, 741994), verbose_name='Дата')),
                ('ostatoc_razvlechenia', models.CharField(max_length=255)),
                ('sum_razvlechenia', models.CharField(max_length=255)),
                ('describe_razvlechenia', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Развлечения',
                'verbose_name_plural': 'Развлечения',
                'ordering': ['-date_razvlechenia', '-id'],
            },
        ),
        migrations.CreateModel(
            name='standart_vichet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hata', models.CharField(max_length=255)),
                ('proezd', models.CharField(max_length=255)),
                ('mobila', models.CharField(max_length=255)),
                ('eda', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Стандартные вычеты',
                'verbose_name_plural': 'Стандартные вычеты',
            },
        ),
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transport', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 15, 741994), verbose_name='Дата')),
                ('ostatoc_transport', models.CharField(max_length=255)),
                ('sum_transport', models.CharField(max_length=255)),
                ('describe_transport', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
                'ordering': ['-date_transport', '-id'],
            },
        ),
    ]
