# Generated by Django 3.0.8 on 2020-10-31 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortizatia',
            name='date_amortizatia',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 44, 937080), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='eda',
            name='date_eda',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 44, 937080), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='minfin',
            name='date_minfin',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 44, 937080), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='nds',
            name='date_nds',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 44, 937080), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='nlg',
            name='date_nlg',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 44, 937080), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='prochee',
            name='date_prochee',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 44, 937080), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='razvlechenia',
            name='date_razvlechenia',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 44, 937080), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='date_transport',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 41, 44, 937080), verbose_name='Дата'),
        ),
    ]
