# Generated by Django 3.0.8 on 2020-11-07 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0002_auto_20201031_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='minfin',
            name='id_insert',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minfin',
            name='type_table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nds',
            name='id_insert',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nds',
            name='type_table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standart_vichet',
            name='itogo',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='amortizatia',
            name='date_amortizatia',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 12, 48, 52, 160260), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='amortizatia',
            name='ostatoc_amortizatia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eda',
            name='date_eda',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 12, 48, 52, 160260), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='eda',
            name='ostatoc_eda',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='minfin',
            name='date_minfin',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 12, 48, 52, 160260), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='minfin',
            name='ostatoc_minfin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='minfin',
            name='sum_minfin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nds',
            name='date_nds',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 12, 48, 52, 165299), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='nds',
            name='ostatoc_nds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nds',
            name='sum_nds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nlg',
            name='date_nlg',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 12, 48, 52, 160260), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='nlg',
            name='text_nlg',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='prochee',
            name='date_prochee',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 12, 48, 52, 160260), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='prochee',
            name='ostatoc_prochee',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='razvlechenia',
            name='date_razvlechenia',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 12, 48, 52, 160260), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='razvlechenia',
            name='ostatoc_razvlechenia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='standart_vichet',
            name='eda',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='standart_vichet',
            name='hata',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='standart_vichet',
            name='mobila',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='standart_vichet',
            name='proezd',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transport',
            name='date_transport',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 12, 48, 52, 160260), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='ostatoc_transport',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
