# Generated by Django 3.0.8 on 2021-02-13 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0003_auto_20201107_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nds',
            options={'ordering': ['-date_nds', '-id'], 'verbose_name': 'Ндс', 'verbose_name_plural': 'Ндс'},
        ),
        migrations.AlterField(
            model_name='amortizatia',
            name='date_amortizatia',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 16, 29, 48, 586718), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='eda',
            name='date_eda',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 16, 29, 48, 583104), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='minfin',
            name='date_minfin',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 16, 29, 48, 581716), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='nds',
            name='date_nds',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 16, 29, 48, 589589), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='nds',
            name='type_table',
            field=models.CharField(blank=True, default='НДС', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nlg',
            name='date_nlg',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 16, 29, 48, 580153), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='prochee',
            name='date_prochee',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 16, 29, 48, 588085), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='razvlechenia',
            name='date_razvlechenia',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 16, 29, 48, 585513), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='date_transport',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 16, 29, 48, 584313), verbose_name='Дата'),
        ),
    ]
