# Generated by Django 3.0.8 on 2021-02-14 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0004_auto_20210213_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortizatia',
            name='date_amortizatia',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 3, 52, 860077), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='eda',
            name='date_eda',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 3, 52, 856813), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='minfin',
            name='date_minfin',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 3, 52, 855567), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='nds',
            name='date_nds',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 3, 52, 862254), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='nlg',
            name='date_nlg',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='prochee',
            name='date_prochee',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 3, 52, 861157), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='razvlechenia',
            name='date_razvlechenia',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 3, 52, 859001), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='date_transport',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 3, 52, 857918), verbose_name='Дата'),
        ),
    ]
