# Generated by Django 3.0.8 on 2021-02-14 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0005_auto_20210214_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortizatia',
            name='date_amortizatia',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 24, 12, 121076), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='eda',
            name='date_eda',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 24, 12, 118685), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='minfin',
            name='date_minfin',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 24, 12, 117819), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='nds',
            name='date_nds',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 24, 12, 122619), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='nlg',
            name='image_nlg',
            field=models.ImageField(blank=True, null=True, upload_to='foto\\%Y\\%m\\%d', verbose_name='Фотоверсия'),
        ),
        migrations.AlterField(
            model_name='nlg',
            name='text_nlg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='prochee',
            name='date_prochee',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 24, 12, 121879), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='razvlechenia',
            name='date_razvlechenia',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 24, 12, 120312), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='date_transport',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 8, 24, 12, 119545), verbose_name='Дата'),
        ),
    ]
