# Generated by Django 3.0.8 on 2021-02-14 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0008_auto_20210214_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minfin',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 21, 34, 38, 95728), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='minfin',
            name='describe',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='minfin',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='minfin',
            name='type_table',
            field=models.IntegerField(blank=True, choices=[(0, 'Еда'), (1, 'Развлечения'), (2, 'Проезд'), (3, 'Телефон'), (4, 'Амортизация'), (5, 'Прочее'), (6, 'НДС')], max_length=255, null=True, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='nlg',
            name='date_nlg',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 21, 34, 38, 95058), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='standartvichet',
            name='eda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Еда'),
        ),
        migrations.AlterField(
            model_name='standartvichet',
            name='hata',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Жильё'),
        ),
        migrations.AlterField(
            model_name='standartvichet',
            name='mobila',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='standartvichet',
            name='proezd',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Проезд'),
        ),
    ]
