# Generated by Django 3.0.8 on 2021-07-26 17:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0009_auto_20210214_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minfin',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Минфин', 'verbose_name_plural': 'Минфин'},
        ),
        migrations.AlterModelOptions(
            name='nlg',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Нлж', 'verbose_name_plural': 'Нлж'},
        ),
        migrations.RemoveField(
            model_name='minfin',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='nlg',
            name='date_nlg',
        ),
        migrations.AddField(
            model_name='minfin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minfin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='nlg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nlg',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='standartvichet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standartvichet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
