# Generated by Django 3.0.8 on 2021-07-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0011_auto_20210726_1900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nlg',
            unique_together={('text_nlg', 'image_nlg')},
        ),
    ]
