# Generated by Django 3.0.8 on 2021-07-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0013_auto_20210726_2000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nlg',
            unique_together=set(),
        ),
    ]
