# Generated by Django 3.0.8 on 2021-07-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0014_auto_20210726_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='minfin',
        ),
    ]
