# Generated by Django 3.0.8 on 2021-08-02 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('B4', '0015_delete_minfin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название плана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('is_active', models.BooleanField(verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['is_active', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_ready', models.BooleanField(verbose_name='Выполнено')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4.Plan')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4.Section')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DefaultTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_ready', models.BooleanField(verbose_name='Выполнено')),
                ('is_default', models.BooleanField(verbose_name='Задача по умолчанию')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4.Plan')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4.Section')),
            ],
            options={
                'verbose_name': 'Задача по умолчанию',
                'verbose_name_plural': 'Задачи по умолчанию',
                'ordering': ['is_default', '-created_at', '-id'],
            },
        ),
    ]
