# Generated by Django 3.0.8 on 2021-08-08 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('B4', '0016_defaulttasks_plan_section_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StandartVichet',
            new_name='DefaultDeductions',
        ),
        migrations.AlterField(
            model_name='defaulttasks',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4.Plan', verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='defaulttasks',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4.Section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4.Plan', verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4.Section', verbose_name='Секция'),
        ),
    ]
