# Generated by Django 3.0.8 on 2021-08-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0017_auto_20210808_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultdeductions',
            old_name='eda',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='defaultdeductions',
            old_name='hata',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='defaultdeductions',
            old_name='mobila',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='defaultdeductions',
            old_name='proezd',
            new_name='travel',
        ),
    ]
