# Generated by Django 3.0.8 on 2021-08-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0018_auto_20210808_0509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nlg',
            new_name='Note',
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Заметки', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='image_nlg',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='text_nlg',
            new_name='text',
        ),
    ]
